name: dashboard-development

channels:
  - conda-forge
  - defaults
  - opensourceeconomics

dependencies:

  - python=3.7
  - pip=19.0.3
  - pandas>=1.0
  - numpy
  - scipy
  - seaborn>=0.10
  - jupyterlab
  - nbsphinx
  - pdbpp
  - xlrd
  - bokeh>=2.0
  - utilities
  - pip:
    - black
    - blackcellmagic
